Add DNS Parser , add test
GPUStore/gpus_agrgtr pull request #19
Opened 2022-11-13 14:42 UTC by SlaykSD

2022-11-14 09:58 UTC, alekseiiagnenkov commented on pom.xml
лишняя строка

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/Parser.java
> +            e.printStackTrace();
может что то типо log.error?

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/GpusAgrgtrApplication.java
> +    public static void main(String[] args)  {
пробел лишний в конце

2022-11-14 09:58 UTC, alekseiiagnenkov commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
Одно и то же

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/config/WebDriverConfiguration.java
> +        System.setProperty("webdriver.edge.driver","src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/resources/msedgedriver1.exe");
Вынеси строки в константы, как минимум эти

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/enumerations/HtmlClassesToParseDNS.java
> +public enum HtmlClassesToParseDNS {
Тебе не кажется, что это имя сюда не подходит? Больше бы подошло SelectPaths или что то такое

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/response/FullDTO.java
> +
лишние строки, много где(проверь еще раз весь код)

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/resources/application.yaml
> +sserver:
серьезно?)

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/resources/application.yaml
> +dns:
Либо приведи к формату technopark, либо technopark приведи к формату dns

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/resources/application.yaml
> +    example: https://www.dns-shop.ru/product/8c12d3e82d96ed20/videokarta-powercolor-amd-radeon-r7-240-axr7-240-2gbd5-hlev2/
Либо приведи к формату technopark, либо technopark приведи к формату dns

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/gpus_agrgtr/parser/videocards/DnsParserTest.java
> +        webDriver = Mockito.mock(WebDriver.class);
Дважды мокируешь одно и то же

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/gpus_agrgtr/parser/videocards/DnsParserTest.java
> +        dnsParser = Mockito.spy(dnsParser1);
думаю можно объединить в одну строчку, но не критично

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/gpus_agrgtr/parser/videocards/DnsParserTest.java
> +        String name2 =  "PALIT GEFORCE GT 730 SILENT LP [NEAT7300HD46-2080H] [PCI-E 2.0, 2  GDDR3, 64 , DVI-D, HDMI, VGA (D-SUB), GPU 902 ]";
слишком длинное, перенеси на новую строку, желательно максимум 120 символов

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +public class DnsParser extends Parser {
Расставь в этом файле методы по порядку вызова.  А то не удобно бегать по всему файлу и искать их)

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +    //Todo:add multithreading : = :
Добавь задачу в проекте и удали эту строку

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            Thread.sleep(DEFAULT_WAIT);
Это для имитации человека?

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +        }
Может эту часть стоит сдвинуть к thread.sleep()?

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            return Integer.parseInt(element.attr(HtmlClassesToParseDNS.PAGINATION_ATTRIBUTE
Я бы вынес этот поиск в отдельную переменную, а потом передал бы ее в Integer.parse

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            return 0;
Это реальный кейс, что у нас может не найтись этот элемент?

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                if (numberOfPage - 1 > 1) {
Можно упростить

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                if (numberOfPage - 1 > 1) {
+ не особо понятно, зачем это

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +        return page.select(HtmlClassesToParseDNS.PATH_FOR_COSTS.getClassName()).stream()
Разве это нельзя упростить? Все ли проверки важны?

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                                .name(Objects.requireNonNull(parameter.selectFirst(HtmlClassesToParseDNS.PARAM_NAME_CLASS.getClassName())).text())
Опять же длинные строки

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                List<String> names = getNames(page).stream().map(DnsParser::getReplacedName).toList();
выглядит так, будто getNames не справляется со своими обязанностями

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                        log.info(e.getMessage());
Почему бы не добавить в один?

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
parallel тут точно помогает?

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            WebDriverWait finalWebDriverWait = webDriverWait;
Есть правило о том, что переменные желательно объявлять перед их использованием. Зачем выше webDriverWait?

2022-11-14 09:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            webDriverWait = new WebDriverWait(webDriver, current.plus(Duration.ofSeconds(EXTRA_TIME_AS_SECONDS)));
По моему это можно просто вынести под do

2022-11-14 10:24 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +        }
Можно и так

2022-11-14 10:26 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            WebDriverWait finalWebDriverWait = webDriverWait;
Это нужно для создания effectively final поля

2022-11-14 10:27 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
Этот код можно улучшить, если знаешь как - предлагай.

2022-11-14 10:31 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            return Integer.parseInt(element.attr(HtmlClassesToParseDNS.PAGINATION_ATTRIBUTE
Это проблема связано с подгрузкой сайта через селениум. Это можно вынести но проверка на null все равно будет. Ты просто увеличишь объем кода без определенной причины

2022-11-14 10:31 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            Thread.sleep(DEFAULT_WAIT);
Код же линейно работает, или я что то не понял? Тип если страница не прогрузится, то она не полностью считается твоим приложением? Не зависит ли твое время ожидания от скорости интернета?

2022-11-14 10:31 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            return 0;
Да, тогда не будет загрузки страницы

2022-11-14 10:32 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +        return page.select(HtmlClassesToParseDNS.PATH_FOR_COSTS.getClassName()).stream()
В идеале можно

2022-11-14 10:32 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
Вопрос не про улучшение, а про использование тут parallel, уверен ли ты в том, что время на его генерацию не будет больше времени линейной обработки?

2022-11-14 10:34 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/enumerations/HtmlClassesToParseDNS.java
> +public enum HtmlClassesToParseDNS {
Нет

2022-11-14 10:36 UTC, SlaykSD commented on src/main/resources/application.yaml
> +sserver:
Очепятка

2022-11-14 10:37 UTC, SlaykSD commented on src/main/resources/application.yaml
> +dns:
Ок

2022-11-14 10:38 UTC, SlaykSD commented on src/main/resources/application.yaml
> +    example: https://www.dns-shop.ru/product/8c12d3e82d96ed20/videokarta-powercolor-amd-radeon-r7-240-axr7-240-2gbd5-hlev2/
ок

2022-11-14 10:39 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/parser/videocards/DnsParserTest.java
> +        webDriver = Mockito.mock(WebDriver.class);
У меня по-умолчанию что-то не мокировалось. Проверю

2022-11-14 10:39 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/parser/videocards/DnsParserTest.java
> +        dnsParser = Mockito.spy(dnsParser1);
Тебе строки длинными точно не покажутся?

2022-11-14 10:41 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/parser/videocards/DnsParserTest.java
> +        String name2 =  "PALIT GEFORCE GT 730 SILENT LP [NEAT7300HD46-2080H] [PCI-E 2.0, 2  GDDR3, 64 , DVI-D, HDMI, VGA (D-SUB), GPU 902 ]";
Здесь 86 символов без пробелом, 96 если считать с пробелами

2022-11-14 10:45 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/Parser.java
> +            e.printStackTrace();
Тогда уж  твой log.info  заменить

2022-11-14 10:46 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +    //Todo:add multithreading : = :
ок

2022-11-14 10:47 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                if (numberOfPage - 1 > 1) {
ок

2022-11-14 10:47 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                List<String> names = getNames(page).stream().map(DnsParser::getReplacedName).toList();
Да, понял

2022-11-14 10:47 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                        log.info(e.getMessage());
окей

2022-11-14 10:48 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            Thread.sleep(DEFAULT_WAIT);
фунукция webdriver.get() асинхронная

2022-11-14 10:54 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
Чтобы на твой вопрос ответить нужно тестировать. Список элементов для поиска пока один, в идеале их больше поставить. (dalayControl можно сказать experimental функция я ее в issue вынесу) . Это как раз вопрос проверки всех подгружаемых строчек.
Я уверен, что parallel stream полезен, потому что нужно либо использованием функционала работы с element tree самому пробежаться в дереву в поисках нужных элементов либо использовать поиск элементов в дереве параллельно. Html код страницы продукта ~ 2000 строчек.

2022-11-14 10:56 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
experimental потому что она не всегда отрабатывает. Иногда она проверяет - не находит, ждет еще, а ресурс все не подгружается. Хз с чем это связано

2022-11-14 10:58 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            webDriverWait = new WebDriverWait(webDriver, current.plus(Duration.ofSeconds(EXTRA_TIME_AS_SECONDS)));
Не можно. В таком случае она перестанет быть effectively final

2022-11-14 10:59 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            return 0;
Если у нас есть кейс, что сайт не прогрузился - выдаем ошибку , хорошо я добавлю throw

2022-11-14 11:01 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +        return page.select(HtmlClassesToParseDNS.PATH_FOR_COSTS.getClassName()).stream()
Можно если добавить select'oв при поике. Иначе не отработает

2022-11-14 11:02 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                                .name(Objects.requireNonNull(parameter.selectFirst(HtmlClassesToParseDNS.PARAM_NAME_CLASS.getClassName())).text())
Строка 113 символов < 120. Согласно паттерну разработки, которым ты руководствуешься строка в пределах нормы.

2022-11-14 11:03 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/config/WebDriverConfiguration.java
> +        System.setProperty("webdriver.edge.driver","src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/resources/msedgedriver1.exe");
ок

2022-11-14 11:26 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
Надо бы разобраться. Она сейчас некорректно работает? Cколько она может ждать?

2022-11-14 11:26 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
Если она отрабатывает, то можно создать задачку и после вернуться к этому

2022-11-14 11:26 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            return 0;
У тебя этот метод ничего не подгружает. Зачем это тебе тут?

2022-11-14 11:26 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            return 0;
Его задача не выкинуть исключение, а получить количество страниц

2022-11-14 11:26 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +        return page.select(HtmlClassesToParseDNS.PATH_FOR_COSTS.getClassName()).stream()
Почему бы не написать просто селекты сразу в нужные места и не делать instanceof?

2022-11-14 11:26 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                        .findFirst().orElse(null))
Возможно эти внутренности я бы вынес в отдельные методы с говорящими названиями, а то вообще не понятно)

2022-11-14 11:26 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                                .name(Objects.requireNonNull(parameter.selectFirst(HtmlClassesToParseDNS.PARAM_NAME_CLASS.getClassName())).text())
Если тебе удобно читать такие строки -  то ок.

2022-11-14 11:26 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                .forEach(group -> fullDTOList.add(FullDTO.builder()
Ощущение, что то, что в foreach было бы не плохо вынести в отдельный метод

2022-11-14 13:43 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +        return page.select(HtmlClassesToParseDNS.PATH_FOR_COSTS.getClassName()).stream()
Настроение такое было

2022-11-14 13:44 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
Она отрабатывает  нормально, иначе бы я ставил ожидание по-умлчанию

2022-11-14 13:45 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
Но если соединение низкое высока вероятность что отработает плохо)

2022-11-14 13:45 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            WebDriverWait finalWebDriverWait = webDriverWait;
Чтобы использовать webDriverWait в parallel stream

2022-11-14 13:48 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            WebDriverWait finalWebDriverWait = webDriverWait;
ок, но выглядит страшно)

2022-11-14 13:52 UTC, garlik6 commented
Нужно еще дату из моего добавитб

2022-11-14 13:52 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/gpus_agrgtr/parser/videocards/DnsParserTest.java
> +        dnsParser = Mockito.spy(dnsParser1);
Можно посерьезнее?

2022-11-14 13:52 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
Ждет она сейчас как положено 500 мс (0,5c) , 2,5c , 4,5c Если последнего не достаточно (7,5 секунд суммарно) прождала, то кидает exception

2022-11-14 13:54 UTC, garlik6 requested changes
Нужно добавить дату из моего

2022-11-14 14:01 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +        return page.select(HtmlClassesToParseDNS.PATH_FOR_COSTS.getClassName()).stream()
Настроение не должно влиять на корректность и правильность кода. Мы можем избежать таких долгих pr, если каждый из нас будет трепетно подходить к своему коду. Не как к штуке, которую залил один раз и забыл, а как к тому, c чем в будущем придется работать(возможно)

2022-11-14 14:10 UTC, SlaykSD commented
> Нужно добавить дату из моего

Дату чего? Дату парсинга? У меня бд без даты

2022-11-14 14:16 UTC, garlik6 approved these changes

2022-11-14 14:56 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                        .findFirst().orElse(null))
Я поменяю на select, будет меньше стримов

2022-11-14 14:57 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            classElements.parallelStream().forEach(classElement -> {
ок

2022-11-14 15:07 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +public class DnsParser extends Parser {
Done

2022-11-14 15:09 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            Thread.sleep(DEFAULT_WAIT);
Окей

2022-11-14 15:18 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                if (numberOfPage - 1 > 1) {
Как упростить?

2022-11-14 15:21 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                if (numberOfPage - 1 > 1) {
Крч я не могу удалить эту проверку. Иначе я буду в конце обработки пробовать получить несущетсвующую страницу. Если ее нет, то мне exception вылетит

2022-11-14 15:28 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/parser/videocards/DnsParserTest.java
> +        webDriver = Mockito.mock(WebDriver.class);
Поправил

2022-11-14 15:28 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/parser/videocards/DnsParserTest.java
> +        dnsParser = Mockito.spy(dnsParser1);
ок

2022-11-14 15:35 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +    //Todo:add multithreading : = :
Не вижу эту задачу! Жми resolve, когда выполнишь

2022-11-14 15:37 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                if (numberOfPage - 1 > 1) {
Никто не просит удалять, но разве -1 нельзя перенести в другую сторону? И цифру с другой стороны назвать как то "говоряще", а то сходу сложно понять зачем это вообще тут

2022-11-14 15:40 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/enumerations/HtmlClassesToParseDNS.java
> +public enum HtmlClassesToParseDNS {
@garlik6 а ты что думаешь?

2022-11-14 16:05 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +    //Todo:add multithreading : = :
Я issue добавил

2022-11-15 04:33 UTC, alekseiiagnenkov reviewed
Провекра не закончена, так как методы не расположены в порядке вызова в DNSParser

2022-11-15 04:33 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                .forEach(group -> fullDTOList.add(FullDTO.builder()
Сборка FullDto - отдельный метод

2022-11-15 04:33 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                log.info("Got pages :{}", costs.size());
Что значит {}?

2022-11-15 04:33 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +public class DnsParser extends Parser {
Не решено, дальнейшую проверку этого файла продолжу после того, как методы будут расположены в порядке вызова

2022-11-15 06:11 UTC, SlaykSD commented on src/main/resources/application.yaml
> +dns:
Тогда я тебя не понимаю. Объясни нормально. Я убрал отличающиеся поля, теперь их  формат одинаковый.

2022-11-15 06:12 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                .forEach(group -> fullDTOList.add(FullDTO.builder()
Не согласен, объясни почему так лучше.

2022-11-15 06:14 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/GpusAgrgtrApplication.java
> +    public static void main(String[] args)  {
Что не исправлено? где ты хочешь пробел?

2022-11-15 06:14 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/response/SpecificationsDTO.java
> +    Double netWeight;
ок

2022-11-15 06:17 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +
Эту строку я не писал

2022-11-15 06:18 UTC, SlaykSD commented on src/main/resources/application.yaml
> +    url: jdbc:postgresql://localhost:5433/gpus_db
У меня не работает этот порт, могу этим закинуть 5432

2022-11-15 06:42 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                log.info("Got pages :{}", costs.size());
вместо скобок вставляется текст после запятой

2022-11-15 06:43 UTC, alekseiiagnenkov commented on src/main/resources/application.yaml
> +dns:
Виноват, все ок, не увидел. Думал, что доступ к технопарку: spring.technopark...
А к днс:
dns...

Зря быканул получается

2022-11-15 06:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                log.info("Got pages :{}", costs.size());
Понял, а в чем разница с log.info("Got pages : " +  costs.size()); ?

2022-11-15 07:17 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +                log.info("Product saved: {}" ,product.getName(), product.getStores());
Они не сольются в одно?

2022-11-15 07:17 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/enumerations/HtmlClassesToParseDNS.java
> +public enum HtmlClassesToParseDNS {
У тебя в enum содержатся пути для объектов, соответственно это можно назвать как SelectPathsToHtmlClasses(но слишком большое и избыточное, потому что select path он специально для html, это очевидно). По этому я считаю, что достаточно SelectPaths. Чем тебе не нравится это название? Объясни плиз

2022-11-15 07:17 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +public class DnsParser extends Parser {
Все еще не решено:

после getAllProducts должно быть getPageWithDefaultWait

2022-11-15 07:40 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/enumerations/HtmlClassesToParseDNS.java
> +public enum HtmlClassesToParseDNS {
Как раз названия div - контейнеров и  a - ссылок. Кажется даже лучше убрать обозначения path

2022-11-15 08:19 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                log.info("Got pages :{}", costs.size());
https://stackoverflow.com/questions/10555409/logger-slf4j-advantages-of-formatting-with-instead-of-string-concatenation

2022-11-17 05:25 UTC, alekseiiagnenkov reviewed
Есть пробелы пустые, если найдешь- исправь, специально не ищи, потом сам исправлю, если буду видеть. 

Метод getLinks должен быть до getNames вроде

2022-11-17 05:25 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +        return Integer.parseInt(className);
странно читать, что из className появляется число. Там точно имя класса хранится в String? Если там число, то так и напиши, что там число)

2022-11-17 05:25 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                .select(HtmlClasses.SUB_FOR_COSTS_CLASS.getClassName())
Я все еще считаю, что это нужно заменить на select path. Тут как бы ничего страшного наверное нет, но это как получать число 4 путем сложения 1+1+1+1 (идти по маленьких шагам, а не сразу получить результат)

2022-11-17 05:25 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +    public static String getReplacedName(String strn) {
что за strn?

2022-11-17 05:25 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                default -> strn;
На самом деле очень сложно понять, что тут происходит. Ты делаешь replace?

2022-11-17 05:25 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +    private boolean delayControl(List<String> classElements) {
На самом деле этот метод выглядит очень страшно. Если есть возможность сделать его более читабельным, но я бы приложил все усилия. Минимум -  дать более точные названия для list, String s и флагов, а то не особо понятно, что это

2022-11-17 05:25 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +public class DnsParser extends Parser {
ctrl+alt+l плиз для этого класса

2022-11-17 05:25 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                                        .build()
В отдельный метод бы это

2022-11-17 05:25 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +    private FullDTO getFullDTOOfElement(Element groupElement) {
Мне бы хватило названия getFullDTO, но можешь оставить и так, если тебе кажется, что текущий нейминг хороший

2022-11-17 13:04 UTC, garlik6 approved these changes

2022-11-17 18:50 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            if (numberOfPage <= countPages) {
Должно, мы обсуждали этот момент

2022-11-17 18:50 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +        return Integer.parseInt(className);
ладно

2022-11-17 18:51 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +    public static String getReplacedName(String strn) {
поменяю на name

2022-11-17 18:52 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                default -> strn;
да , в сигнатуре четко сказано

2022-11-17 18:53 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                default -> strn;
Делает перевод строки формат GEFORCE RTX 3060 [ какой-то серийник ] [какие-то данные] -> GEFORCE RTX 3060 ( какой-то серийник )

2022-11-17 18:53 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                default -> strn;
Есть соответствующий кейс в тестах

2022-11-17 18:54 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +    private boolean delayControl(List<String> classElements) {
дам, но эта функция уже в issue

2022-11-17 18:54 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +    private FullDTO getFullDTOOfElement(Element groupElement) {
Окей сделаю getFullDTO

2022-11-17 18:55 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +                                        .build()
ладно

2022-11-20 04:22 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/GpusAgrgtrApplication.java
> -@SpringBootApplication
Мы убираем spring из этого сервиса?

2022-11-20 04:22 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/parser/videocards/dns/DnsParser.java
> +            if (numberOfPage <= countPages) {
Можешь ещё раз объяснить зачем? У меня такого нет в коде. У тебя в for стоит такая же проверка.

2022-11-20 07:51 UTC, alekseiiagnenkov approved these changes

2022-11-20 07:51 UTC, merged