added date to stores
GPUStore/gpus_agrgtr pull request #20
Opened 2022-11-13 15:58 UTC by garlik6

2022-11-14 04:12 UTC, alekseiiagnenkov reviewed
+ не увидел тестов. Надо бы проверить корректность

2022-11-14 04:12 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
>                  if (prod != null) {
Тут проблемы с логикой, если мы попадаем на строчку с логированием, то с продуктом ничего не происходит (он не сохраняется и не апдейтится)

2022-11-14 04:12 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
>      public void save(List<Product> products) {
Я бы на самом деле разделил этот метод на 2, update и create. Сделаешь?

2022-11-14 04:14 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
>                  }
Тут проблемы с логикой, если мы попадаем на строчку с логированием, то с продуктом ничего не происходит (он не сохраняется и не апдейтится)

2022-11-14 04:14 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
>      public void save(List<Product> products) {
Я бы на самом деле разделил этот метод на 2, update и create. Сделаешь?

2022-11-15 20:54 UTC, garlik6 commented
Tests in progress

2022-11-16 18:35 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/entity/Parameter.java
> -@Data
Убрал так как это было причиной вот этих исключений при дебаге что очень сильно его замедляет
![photo_5449863425162331513_y](https://user-images.githubusercontent.com/56256488/202264438-618464b2-d986-4290-99ad-24d214694429.jpg)

2022-11-16 19:39 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/entity/Parameter.java
> -@Data
Разве без этой аннотации hibernate так же не передаст класс с массивами массивов грубо говоря?

2022-11-16 19:45 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/entity/Parameter.java
> -@Data
Знаешь почему? @Data создает toString(), по этому он бесконечно вызывал toString(). Без @Data этот метод не определен.

2022-11-16 20:17 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    }
Ты можешь написать что-то типо:

```
Optional<Product> prod = productRepository.findProductByName(productName)
.orElse(findProductByCategories(categoryExtractor.extractCategorySet(productName)));
if (prod.isPresent()) {
    return prod;
}
return Optional.empty();
```

На твое усмотрение, можешь оставить как есть

2022-11-16 20:17 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        System.out.println();
Думаю это тут не должно быть)

2022-11-16 20:17 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        oldProduct.getStores().addAll(newProduct.getStores());
Не может ли произойти тут дублирование магазинов? У нас же это обычный лист, он не следит за тем, что могут быть вставлены копии. Эта задача только на нас

2022-11-16 20:17 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        }
Я бы обязательно бы поменял имя prod хотя бы на optionalProduct или на какое то более говорящее имя.

Или можно сделать: 
        
 ```
        Store store = product.getStores.get(0);
        product = find(product.getName()).orElse(product);
        if(!product.getStores().contains(store)){ //хотя думаю это может не сработать(надо правильно определить сравнение)
                 product.getStores().add(store);
        }
        productRepository.save(product);
```

2022-11-16 20:17 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +                .setDate(Date.from(Instant.now()));
На самом деле думаю их создание можно вынести в отдельный класс. Или хотя бы в отдельный метод в этом классе(используется несколько раз)

2022-11-16 22:10 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        oldProduct.getStores().addAll(newProduct.getStores());
У каждого нового магазина своя дата так что не продублируется

2022-11-16 22:11 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/GpusAgrgtrApplication.java
> +            parser.parse().forEach(productService::save);
Так легче тестировать ну и функция save а не save all

2022-11-16 22:16 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    }
По мне так слишком вложено сверху лучше логика просматривается

2022-11-16 22:20 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/entity/Parameter.java
> -@Data
Понял

2022-11-16 22:21 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        oldProduct.getStores().addAll(newProduct.getStores());
Сейчас это уже не магазин, а скорее запись о цене вопределенном магазине в определннное время

2022-11-16 22:23 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    }
Мне больше вариант Леши нравится

2022-11-16 22:24 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/entity/Parameter.java
> -@EqualsAndHashCode
Пока не сравнивается потом можно будет добавить

2022-11-17 04:06 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/GpusAgrgtrApplication.java
> +            parser.parse().forEach(productService::save);
а в каком случае это saveAll? Разницы никакой кроме того, что stream создается

2022-11-17 04:09 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/entity/Parameter.java
> -@EqualsAndHashCode
ок

2022-11-17 04:16 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    }
@garlik6 на самом деле если конкретно знать, что происходит, то это читается легко

2022-11-17 04:20 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        oldProduct.getStores().addAll(newProduct.getStores());
А понял. Но может нам это сохранять только если цена изменилась? Через код у каждого продукта будет больше чем 365 записей о магазинах

2022-11-17 07:04 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/GpusAgrgtrApplication.java
> +            parser.parse().forEach(productService::save);
Это скорее итератор

2022-11-17 07:41 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/GpusAgrgtrApplication.java
> +            parser.parse().forEach(productService::save);
понял, ок

2022-11-19 07:29 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    }
orElse() возращает Product а не Optional<Product>

2022-11-19 07:35 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    }
да, забыл, но это особо сути не меняет:

```
private Product find(String productName) {
Product product = productRepository.findProductByName(productName)
.orElse(findProductByCategories(categoryExtractor.extractCategorySet(productName)));
return product;
```

2022-11-19 08:21 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        oldProduct.getStores().addAll(newProduct.getStores());
Не решено

2022-11-19 12:36 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    }
findProductByCategories() Возвращает Optional<Product>, так что проверять все равно придется 
orElse нужен скорее для дефолтной заглушки, а не для следующего шага поиска

2022-11-19 12:58 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    }
Зачем ему возвращать optional? Он может вернуть product, а проверки is present можно заменить на == null.

2022-11-19 13:00 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    }
Код, который я предлагаю выглядит аккуратнее, лично по мнению. Дену он тоже больше понравился. Есть какие то серьезные проблемы почему так нельзя сделать?

2022-11-19 17:02 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +                .collect(Collectors.groupingBy(Store::getName))
Зачем, если в бд должно все храниться корректно? Я не прав?

2022-11-19 17:02 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +                .collect(Collectors.groupingBy(Store::getName))
Можешь написать объяснения почему метод должен быть таким?

2022-11-19 21:24 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +                .collect(Collectors.groupingBy(Store::getName))
Примеры зааписей в бд store для одного продукта
| name     | Price| Date|
| ----------- | ----------- |----------------|
| A    | 100    |10.10|
| B    | 120    |10.10|
| A    | 90    |11.10|
| B    | 80    |11.10|
| A    | 110    |12.10|
| B    | 90   |12.10|

Нам нужно найти цену для самой поздней записи для каждого магазина

2022-11-19 21:46 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +                .collect(Collectors.groupingBy(Store::getName))
3) Выделяем из найденных последних по дате записей цену
``` java
                                .getCost()
                ));
``` 
4) На вход поступает новый продукт, допустим у него список магазинов такой
: 
| name  of the store    | Price| Date|
| ----------- | ----------- |----------------|
| A    | 110    |13.10|
| B    | 200   |13.10|
Для каждой из этих записей проверяем ести ли запись с таким названием магазина в нашей мапе
и если есть и цена не совпадает мы добавляем в список магазинов наш продукт
``` java
        newProduct.getStores()
                .forEach(store -> {
                    double newStorePrice = store.getCost();
                    Double oldStoreLastPrice = eachStoreLastPriceGroupedByName.get(store.getName());
                    if (oldStoreLastPrice != null && !oldStoreLastPrice.equals(newStorePrice)) {
// Сравниваем и понимаем, для A c новой датой мы не вставляем , так как эта дата повторяется.
//а для B цена повысилась значит вставляем
                        store.setProduct(oldProduct);
                        oldProduct.getStores().add(store);
                    }
                });
    }
```

2022-11-19 21:50 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +                .collect(Collectors.groupingBy(Store::getName))
Заметил пока писал что если магазина раньше не было он не добавляется, нужно добавить тест на это и учесть

2022-11-19 21:51 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +                .collect(Collectors.groupingBy(Store::getName))
Предложения по оптимизации принимаются

2022-11-19 22:23 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +                .collect(Collectors.groupingBy(Store::getName))
Ну и можно на функции разделить для понятности

2022-11-20 03:41 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +                .collect(Collectors.groupingBy(Store::getName))
1. У добавляемого продукта всегда только 1 магазин.
2. Не достаточно ли будет взять и найти первый магазин с таким же именем с конца и просто сравнить цену?

2022-11-20 07:39 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +                .collect(Collectors.groupingBy(Store::getName))
1) Но передается лист магазинов

2) Что значит первый с конца
В бд не сохраняется порядок

2022-11-20 17:21 UTC, alekseiiagnenkov approved these changes

2022-11-21 17:20 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
>  @Slf4j
Ради чего ты ставишь эту аннотацию если у тебя нету ни одного лога

2022-11-21 17:25 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    private void populate(Product product) {
В чем суть метода? Он добавляет каждой категории указатель но новый продукт и ставит дату? Это разве оно про "населять" .  У тебя метод делает настройку референсов в many-to-many И добавляет дату. Мне кажется имеет смысл разделить на два метода с соответствующим названиями

2022-11-21 17:27 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        if (newProduct.getStores().size() != 1) {
У нас же возможно один и тот же продукт будет иметь несколько магазинов. В чем проблематичность этого?

2022-11-21 17:31 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    private static Product newProduct3;
Смотреть страшно , зачем тебе в статическом контексте? Это тестовые данные. Ты каждый раз создаешь новые

2022-11-21 17:33 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveNewProduct() {
Это ужас. В чем смысл такого тестирования? Расскажи пожалуйста

2022-11-21 17:35 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
Это тест на что? На работу ArgumentCapptor'a?

2022-11-21 17:35 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void testingSubjects() {
И ты все-все эти сущности проверяешь, ага?

2022-11-21 17:36 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +                .setName("lasdjfldsjfl; a;lsdjfla;skdjfl laskdjf;lsakdfj")
Классное название

2022-11-21 17:36 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        if (newProduct.getStores().size() != 1) {
Новый продукт должен иметь только 1 магазин

2022-11-21 17:39 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveNewProduct() {
Попрошу выражаться аккуратнее. Не стоит оскорблять чужую работу

2022-11-21 17:41 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    private void populate(Product product) {
Судя по твоей логике лучше подходит correctProduct

2022-11-21 17:43 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        if (newProduct.getStores().size() != 1) {
Тогда какой метод должен обновлять список магазинов?

2022-11-21 17:45 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        if (newProduct.getStores().size() != 1) {
Соглашусь, можно взять название moveStores. Что думаешь?

2022-11-21 17:58 UTC, SlaykSD requested changes

2022-11-21 17:58 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    private void populate(Product product) {
Кстати о приведении в корректный формат. Я создаю новую сущность, добавляю туда данные. Я тоже привожу сущность в корректный формат?

2022-11-21 17:58 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    private void populate(Product product) {
Может нам тогда не setFullDTO писать а populate к примеру

2022-11-21 17:58 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
>  class ProductServiceTest {
Расскажи пожалуйста о своих тестах. Я не могу понять что ты тестируешь.

2022-11-21 18:00 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
>  @Slf4j
в будущем она точно пригодится, но если она тебя смущает

2022-11-21 18:02 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    private void populate(Product product) {
setFullDto - это сеттер, это совсем другое в данном случае

2022-11-21 18:14 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
>  @Slf4j
Мне кажется, что если мы пишем независимые MR, то все части измененные в ходе MR должны быть на тот момент конечными. Да появится в  будущем таска - доделать логирование. Но тогда с таким же успехом можно , например, надбавлять ненужных зависимостей в pom, просто чтобы было, но проект станет нагруженным. И это будет до тех пор, пока кто-нибудь не напишет реализацию этих зависимостей

2022-11-21 18:18 UTC, SlaykSD commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +        if (newProduct.getStores().size() != 1) {
Можно оставить update, но дописать, что конкретно обновляет. Например updateNewProductStories

2022-11-21 18:29 UTC, garlik6 commented on src/main/java/ru/mephi/gpus_agrgtr/rest/services/ProductService.java
> +    private void populate(Product product) {
populate это тип наполнить

2022-11-21 18:32 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    private static Product newProduct3;
До этого был запрос на то, чтобы убрать из тестов создание одинаковых магазинов в каждом тесте и вынести их наружу. В данном случае выбор сделан в то чтобы было минимально кода, а не минимально объектов в тесте

2022-11-21 18:40 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    private static Product newProduct3;
У Алексея прекрасно получилось решить эту проблему при помощи вспомогательных классов-утилит. Думаю тебе следую поступить так же. Так же тестовые сущности, которые создает его классы-утилиты - нестатические экземпляры.

2022-11-21 18:41 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    private static Product newProduct3;
Они не хранятся в памяти, а создаются по необходимости.

2022-11-21 18:50 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
А так же на то, что при добавлении магазина корректyо сработал метод populate (у всех магазинов и категорий, в том числе добавленного есть ссылка на нужный продукт и есть дата у магазина)

2022-11-21 18:51 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
Уточню:
Да. ты выделил блок save  в отдельный, но ты хочешь проверить какую-то часть работы ORM?
У тебя репозиторий  - mock. То есть он у тебя отделен от всех функции которые он вызывает. 
Хорошо, но что ты хочешь у него проверить?  Что он возращает ту же сущность, что и  пытается сохранить?

2022-11-21 18:53 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
Такое чувство, что ты не доверяешь библиотеке и тестируешь ее, а должен свою логику тестировать.

2022-11-21 18:56 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
А если мы говорим про тестирование взаимодействия hibernate и нашего кода, то здесь:
- Если уж интеграционный писать (И учитывать, что наша бд из yaml - тестируемая бд), то надо поднимать spring context для этого пишем @SpringBootTest и repository должен быть не моком, а @Authowired

2022-11-21 18:58 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
Если непонятно - давай на созвоне поясню

2022-11-21 19:00 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
Ты хочешь понять зачем нужен ArgumentCaptor?

2022-11-21 19:02 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
Я передаю в метод продукт рандомный
Мой метод делает с ним какие-то манипуляции, как то его изменяет, возможно сохраняет даже не его.

2022-11-21 19:03 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +                .setName("lasdjfldsjfl; a;lsdjfla;skdjfl laskdjf;lsakdfj")
Можно сделать код читабельнее и прописать конкретные названия?

2022-11-21 19:03 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
Что я хочу проверить с помощью каптора это то что в итоге пойдет в базу данных после всех моих манипуляций

2022-11-21 19:04 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
И да это метод save не репозитория а сервиса

2022-11-21 19:04 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
Мне кажется тебе это было не понятно

2022-11-21 20:02 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    void saveExistingProduct() {
Так @garlik6 и @SlaykSD, прерву вашу дискусию, скоро сделаю так, чтобы чисто на тесты поднималась тестовая бд. Так что можно оставить тесты интеграционными

2022-11-21 20:03 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +                .setName("lasdjfldsjfl; a;lsdjfla;skdjfl laskdjf;lsakdfj")
someName -  будет вполне достаточно

2022-11-23 11:48 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/AbstractTest.java
> +        }
ну честно говоря , если это прям обобщить - неизвестно в каком порядке каждый список. То есть сначала сортировка в естественный порядок, потом сравнение. И я бы сделал отдельный метод дженерик функцию по обработке коллекции

2022-11-23 11:49 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/AbstractTest.java
> +        }
Сам же видишь, что одно и то же делаешь

2022-11-23 11:55 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
>      private static ProductService productService;
Где аннотация injectsMock?

2022-11-23 11:57 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    private static final ProductTestData td = new ProductTestData();
Зачем? Почему ты не хочешь сделать методы static?

2022-11-23 11:58 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +        productService = new ProductService(productRepository, categoryExtractor, dateUtils);
Зачем это делать для каждого теста? Это разве обнуялет какие-то параметры?

2022-11-23 12:08 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +        productService = new ProductService(productRepository, categoryExtractor, dateUtils);
@InjectMocks не работает
@BeforeAll не подойдет, так как используется this

2022-11-23 12:10 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +        productService = new ProductService(productRepository, categoryExtractor, dateUtils);
@ExtendWith(SpringExtension.class)
И должно заработать

2022-11-23 12:12 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +        productService = new ProductService(productRepository, categoryExtractor, dateUtils);
![image](https://user-images.githubusercontent.com/56256488/203543913-b20c6bea-3ffa-4427-a55d-5c2a84370128.png)

2022-11-23 12:12 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +        productService = new ProductService(productRepository, categoryExtractor, dateUtils);
А вообще если используешь эту аннотацию тебе beforeEach вообще не нужен

2022-11-23 12:13 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +        productService = new ProductService(productRepository, categoryExtractor, dateUtils);
![image](https://user-images.githubusercontent.com/56256488/203544071-6c071df7-0bcf-494c-a938-689a738d694d.png)

2022-11-23 12:13 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +        productService = new ProductService(productRepository, categoryExtractor, dateUtils);
Ошибки при inject Mocks
Если запускать тесты по одному все работает
Если все вместе вот это

2022-11-23 12:16 UTC, SlaykSD commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +        productService = new ProductService(productRepository, categoryExtractor, dateUtils);
Короче, как знаешь. Мне кажется можно это улучшить с точки зрения логики кода

2022-11-23 20:13 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/rest/services/ProductServiceTest.java
> +    private static final ProductTestData td = new ProductTestData();
Потому что листы взаимосвязаны, и нужно чтобы они создавались одновременно

2022-11-23 20:13 UTC, garlik6 commented on src/test/java/ru/mephi/gpus_agrgtr/AbstractTest.java
> +        }
Это не моё)

2022-11-23 20:34 UTC, SlaykSD approved these changes

2022-11-24 08:03 UTC, merged